spring:
  gateway:
    routes:
    - id: cns
      uri: lb://cloud-native-spring
      predicates:
      - Path=/api/**
      filters:
       - RewritePath=/api/(?<segment>.*), /$\{segment}
    - id: cns-ui
      uri: lb://cloud-native-spring-ui
      predicates:
      - Path=/ui/**
      filters:
      - RewritePath=/ui/(?<segment>.*), /$\{segment}
