spring:
  gateway:
    routes:
    - id: cns
      uri: lb://cloud-native-spring
      predicates:
      - Path=/api
    - id: cns-ui
      uri: lb://cloud-native-spring-ui
      predicates:
      - Path=/ui
