spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cloud-native-spring
          uri: lb://cloud-native-spring
          predicates:
            - Path=/api/cities/**
          filters:
            - RewritePath=/api/(?<cities>.*), /$\{cities}
