spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cloud-native-spring
          uri: lb://cloud-native-spring
          predicates:
            - Path=/api/cities/**
          filters:
            - RewritePath=/cities/(?<path>.*), /$\{path}
        - id: cloud-native-spring-ui
          uri: lb://cloud-native-spring-ui
          predicates:
            - Path=/ui/**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}
